### ISSUE TITLE
Windows line feeds?

### ISSUE THREAD

**Issue by anyong** [markfinger/python-js-host#6]
Just following the quick start and immediately run into this error:

```
>>> settings.configure(USE_MANAGER=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\js_host\conf.py", line 55, in configure
    from .host import host
  File "C:\Python34\lib\site-packages\js_host\host.py", line 8, in <module>
    manager = JSHostManager()
  File "C:\Python34\lib\site-packages\js_host\base_server.py", line 70, in __init__
    self.validate_status()
  File "C:\Python34\lib\site-packages\js_host\base_server.py", line 214, in validate_status
    version = self.get_version().split('.')
  File "C:\Python34\lib\site-packages\js_host\base_server.py", line 117, in get_version
    return self.get_status()['version']
  File "C:\Python34\lib\site-packages\js_host\base_server.py", line 113, in get_status
    self.status = self.read_config_file(self.get_path_to_config_file())
  File "C:\Python34\lib\site-packages\js_host\base_server.py", line 104, in read_config_file
    raise ConfigError(stderr)
js_host.exceptions.ConfigError: b'C:\\dev\\project\\static\\node_modules\\.bin\\js-host:2\r\nbasedir=`dirname "$0"`\r\n        ^\r\nSyntaxError: Unexpected token ILLEGAL\r\n    at exports.runInThisContext (vm.js:73:16)\r\n    at Module._compile (module.js:443:25)\r\n    at Object.Module._extensions..js (module.js:478:10)\r\n    at Module.load (module.js:355:32)\r\n    at Function.Module._load (module.js:310:12)\r\n    at Function.Module.runMain (module.js:501:10)\r\n    at startup (node.js:129:16)\r\n    at node.js:814:3\r\n'
```

**Comment by markfinger** [comment]
I suppose we could detect windows and append `.cmd` to the BIN

**Comment by anyong** [comment]
Ok, it seems like there is more to the story here... `base_server.py line 96` originally had `self.path_to_node` as an argument, and I had to remove that to get js_host working with the path `.bin/js-host.cmd` business. That was because if i ran `node path/to/node_modules/.bin/js-host.cmd` I would get all kinds of errors. Actually if it's running from node, it should just run `node path/to/node_modules/js-host/bin/js-host.js`. The first way, I had to manually start the js-host command from the CLI, and the second way, django automatically spins up the js-host server when I run `python manage.py runserver` - that's much better.

I'm determined to get this stuff working on my Windows machine! If you want to include any of these fixes in the packages directly I'm happy to test them out. Thanks.

**Comment by markfinger** [comment]
Well, I've managed to get the js-host test suite running under windows, so I'll take a stab at this

**Comment by markfinger** [comment]
It's working on an old XP box now, but I suspect that there will be more issues with later versions & powershell, so I'll keep testing

**Comment by markfinger** [comment]
@anyong 

What version of windows are you running?
What's the usual terminal/shell used for windows development these days? Powershell?

**Comment by anyong** [comment]
I use 8.1 with cygwin / bash, but I tried with regular old cmd.exe too and
got the same results.

**Comment by markfinger** [comment]
Thanks. I'll grab a vm and give it a whirl
